In [4]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 6.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.4 MB 6.7 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.4 MB 8.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.4 MB 7.7 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.4 MB 7.7 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.4 MB 7.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.4 MB 6.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 6.7 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
pip install pandas

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 6.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.9 MB 7.6 MB/s eta 0:00:01
   ------------ --------------------------- 3.1/9.9 MB 5.9 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/9.9 MB 4.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 3.7 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 3.4 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 3.2 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 3.1 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 3.0 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.9 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 2.9 MB/s eta 0:00:02
   ----------------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy

In [7]:
import numpy as np


temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:", temperatures_w1)


Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [9]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


print("Shape of temperatures_w1:", temperatures_w1.shape)


Shape of temperatures_w1: (7,)


In [10]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


In [11]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:", temperatures_f)


Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [12]:
max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Maximum Temperature:", max_temp)
print("Minimum Temperature:", min_temp)
print("Mean Temperature:", mean_temp)


Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [13]:
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


weekend_temps = temperatures_w1[-2:]
print("Weekend temperatures:", weekend_temps)


Weekend temperatures: [24.8 21.9]


In [14]:
import numpy as np


temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], 
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   
])


print("2D Temperature Array:")
print(temperatures)


2D Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [15]:
print(temperatures.shape)


(2, 7)


In [16]:
import numpy as np

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]  
])

print("Shape:", temperatures.shape)

print("Data type:", temperatures.dtype)



Shape: (2, 7)
Data type: float64


In [17]:
print("Total elements:", temperatures.size)
week1 = temperatures[0]
print("Week 1 temperatures:", week1)
week2 = temperatures[1]
print("Week 2 temperatures:", week2)


Total elements: 14
Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [18]:
weekend_temps = temperatures[:, -2:]
print("Weekend temperatures for both weeks:")
print(weekend_temps)


Weekend temperatures for both weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [19]:
import pandas as pd


marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [21]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [22]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])


Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [23]:
print(marks.iloc[2])


89


In [24]:
high_marks = marks[marks > 90]
print(high_marks)


Rank1    95
Rank2    92
dtype: int64


In [25]:
import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

marks.loc['Rank1'] = 100
print(marks)

marks = marks.drop('Rank5')
print(marks)

cgpa = marks / 10
print(cgpa)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [26]:
import pandas as pd

# Creating the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Display the DataFrame
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [27]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': [
        'Electronics','Clothing','Electronics','Furniture',
        'Clothing','Electronics','Furniture','Clothing',
        'Furniture','Electronics'
    ],
    'Region': [
        'North','South','North','East','West',
        'North','East','West','South','North'
    ],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})


In [28]:
print(transactions)
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)



   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [29]:
print(transactions[['ProductCategory', 'Amount']])


  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [30]:
print(transactions.iloc[:, -3:])


  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [31]:
filtered_data = transactions[
    (transactions['Region'] == 'North') & (transactions['Amount'] > 200)
]

print(filtered_data)


   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [32]:
print(transactions['ProductCategory'].value_counts())


ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [33]:
print(transactions['Region'].unique())
['North' 'South' 'East' 'West']
region_mean = transactions.groupby('Region')['Amount'].mean()
print(region_mean)


<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [34]:
import pandas as pd

transactions = pd.DataFrame({
    'TransactionID': [101,102,103,104,105,106,107,108,109,110],
    'ProductCategory': [
        'Electronics','Clothing','Electronics','Furniture',
        'Clothing','Electronics','Furniture','Clothing',
        'Furniture','Electronics'
    ],
    'Region': [
        'North','South','North','East','West',
        'North','East','West','South','North'
    ],
    'Amount': [200,150,300,450,200,250,300,180,350,400]
})


In [35]:
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [36]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)


   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [37]:
transactions = transactions[transactions['TransactionID'] != 109]
print(transactions)


   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [38]:
transactions.drop(columns='Discount', inplace=True)
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
